# Generated by build_qa_codegen.py
# strategy: emergency_response_scenarios
# func_name: gen_emergency_response_scenarios
# expected_per_row: 3

import random

def gen_emergency_response_scenarios(rows, rng):
    """rows: list[dict]，每个 dict 是 CSV 一行已清洗数据；rng: random.Random 实例。"""
    def is_empty(val):
        return val.strip() in {"", "无", "无资料", "无意义", "未制定标准", "未制订标准", "尚不明确", "暂无", "未提供", "-", "—"}

    out = []
    for row in rows:
        leak = row.get("泄漏处理", "").strip()
        fire = row.get("消防措施", "").strip()
        danger = row.get("危险特性", "").strip()
        chem_name = row.get("_主名", "").strip()

        if is_empty(leak) or is_empty(fire) or is_empty(danger) or is_empty(chem_name):
            continue

        # 场景1: 泄漏处理相关问答
        q1 = f"遇到{chem_name}泄漏时，应该如何处理泄漏现场？"
        a1 = f"针对{chem_name}的泄漏处理措施为：{leak}"
        out.append({"q": q1, "a": a1, "type": "single_field"})

        # 场景2: 消防措施相关问答
        q2 = f"如果发生{chem_name}火灾，应采取哪些消防措施？"
        a2 = f"{chem_name}的消防措施包括：{fire}"
        out.append({"q": q2, "a": a2, "type": "single_field"})

        # 场景3: 综合危险特性与应急处理推理问答
        q3 = f"考虑到{chem_name}具有的危险特性，发生事故时应如何综合应对？"
        a3 = (f"{chem_name}的危险特性是：{danger}。结合泄漏处理和消防措施，"
              f"应迅速撤离泄漏污染区人员，切断火源，避免明火和高热，"
              f"佩戴适当的防护装备，合理通风加速气体扩散，使用适合的灭火剂，"
              f"并妥善收集处理泄漏物，防止二次污染。")
        out.append({"q": q3, "a": a3, "type": "reasoning"})

    return out