# Generated by build_qa_codegen.py
# strategy: exposure_limits_and_toxicology
# func_name: gen_exposure_limits_and_toxicology
# expected_per_row: 3

import random
import re

def gen_exposure_limits_and_toxicology(rows, rng):
    """rows: list[dict]，每个 dict 是 CSV 一行已清洗数据；rng: random.Random 实例。"""
    def is_empty(val):
        return val in ("", "无", "无资料", "无意义", "未制定标准", "未制订标准", "尚不明确", "暂无", "未提供", "-", "—")

    def clean_text(text):
        return text.strip()

    out = []
    for row in rows:
        main_name = row.get("_主名", "").strip()
        if not main_name:
            continue

        exposure = row.get("接触限值", "").strip()
        toxicology = row.get("毒理资料", "").strip()
        route = row.get("侵入途径", "").strip()
        harm = row.get("健康危害", "").strip()

        # Check empty fields
        exposure_valid = not is_empty(exposure)
        toxicology_valid = not is_empty(toxicology)
        route_valid = not is_empty(route)
        harm_valid = not is_empty(harm)

        # Prepare cleaned values
        exposure = clean_text(exposure) if exposure_valid else None
        toxicology = clean_text(toxicology) if toxicology_valid else None
        route = clean_text(route) if route_valid else None
        harm = clean_text(harm) if harm_valid else None

        # Generate Q&A items, aim for 3 per row, mix single and multi field types

        qa_candidates = []

        # 1. Exposure limits related Q&A (single_field)
        if exposure_valid:
            q = f"{main_name}的接触限值有哪些相关标准或数值？"
            a = f"{main_name}的接触限值信息为：{exposure}。"
            qa_candidates.append({"q": q, "a": a, "type": "single_field"})

        # 2. Toxicology related Q&A (single_field)
        if toxicology_valid:
            q = f"{main_name}的毒理资料有哪些重要指标或描述？"
            a = f"{main_name}的毒理资料描述为：{toxicology}。"
            qa_candidates.append({"q": q, "a": a, "type": "single_field"})

        # 3. Exposure routes related Q&A (single_field)
        if route_valid:
            q = f"{main_name}的主要侵入途径有哪些？"
            a = f"{main_name}的侵入途径包括：{route}。"
            qa_candidates.append({"q": q, "a": a, "type": "single_field"})

        # 4. Health hazards related Q&A (single_field)
        if harm_valid:
            q = f"{main_name}对健康有哪些危害？"
            a = f"{main_name}的健康危害描述为：{harm}"
            qa_candidates.append({"q": q, "a": a, "type": "single_field"})

        # 5. Combined exposure limits and toxicology (multi_field)
        if exposure_valid and toxicology_valid:
            q = f"{main_name}的安全暴露限值和毒理特性是什么？"
            a = f"{main_name}的接触限值为：{exposure}；毒理资料显示：{toxicology}。"
            qa_candidates.append({"q": q, "a": a, "type": "multi_field"})

        # 6. Combined toxicology and health hazard (multi_field)
        if toxicology_valid and harm_valid:
            q = f"{main_name}的毒理资料与健康危害有哪些关联？"
            a = f"{main_name}的毒理资料为：{toxicology}，健康危害包括：{harm}"
            qa_candidates.append({"q": q, "a": a, "type": "multi_field"})

        # 7. Combined exposure limits and health hazard (multi_field)
        if exposure_valid and harm_valid:
            q = f"{main_name}的接触限值与健康危害之间有何关系？"
            a = f"{main_name}的接触限值为：{exposure}，健康危害描述为：{harm}"
            qa_candidates.append({"q": q, "a": a, "type": "multi_field"})

        # 8. Combined route and health hazard (multi_field)
        if route_valid and harm_valid:
            q = f"{main_name}的侵入途径和健康危害有哪些？"
            a = f"{main_name}的侵入途径为：{route}，健康危害包括：{harm}"
            qa_candidates.append({"q": q, "a": a, "type": "multi_field"})

        # 9. Combined route and toxicology (multi_field)
        if route_valid and toxicology_valid:
            q = f"{main_name}的侵入途径和毒理资料是怎样的？"
            a = f"{main_name}的侵入途径包括：{route}，毒理资料显示：{toxicology}。"
            qa_candidates.append({"q": q, "a": a, "type": "multi_field"})

        # Select up to 3 Q&A per row with some randomness but consistent order for reproducibility
        if len(qa_candidates) > 3:
            # Use rng to shuffle then pick first 3
            rng.shuffle(qa_candidates)
            selected = qa_candidates[:3]
        else:
            selected = qa_candidates

        out.extend(selected)

    return out