# Generated by build_qa_codegen.py
# strategy: multi_field_comparison
# func_name: gen_multi_field_comparison
# expected_per_row: 2

import random

def gen_multi_field_comparison(rows, rng):
    """rows: list[dict]，每个 dict 是 CSV 一行已清洗数据；rng: random.Random 实例。"""
    def is_empty(val):
        return val in ("", "无", "无资料", "无意义", "未制定标准", "未制订标准", "尚不明确", "暂无", "未提供", "-", "—")

    def try_float(val):
        try:
            return float(val)
        except:
            return None

    out = []
    for row in rows:
        # 过滤字段
        mp = row.get("熔点（℃）", "").strip()
        bp = row.get("沸点（℃）", "").strip()
        fp = row.get("闪点（℃）", "").strip()
        flm = row.get("燃烧性", "").strip()
        name = row.get("_主名", "").strip()

        # 跳过空值字段
        if is_empty(name):
            continue

        # 解析数值字段
        mp_v = try_float(mp) if not is_empty(mp) else None
        bp_v = try_float(bp) if not is_empty(bp) else None
        fp_v = try_float(fp) if not is_empty(fp) else None
        flm_v = flm if not is_empty(flm) else None

        # 收集有效字段
        fields = {}
        if mp_v is not None:
            fields["熔点（℃）"] = mp_v
        if bp_v is not None:
            fields["沸点（℃）"] = bp_v
        if fp_v is not None:
            fields["闪点（℃）"] = fp_v
        if flm_v is not None:
            fields["燃烧性"] = flm_v

        # 至少两个字段才生成比较问答
        if len(fields) < 2:
            continue

        # 准备比较字段列表（数值和分类分开）
        num_fields = [k for k in ["熔点（℃）", "沸点（℃）", "闪点（℃）"] if k in fields]
        cat_fields = ["燃烧性"] if "燃烧性" in fields else []

        # 生成问答1：数值字段两两比较
        num_pairs = []
        for i in range(len(num_fields)):
            for j in range(i+1, len(num_fields)):
                f1, f2 = num_fields[i], num_fields[j]
                v1, v2 = fields[f1], fields[f2]
                if v1 is None or v2 is None:
                    continue
                diff = abs(v1 - v2)
                if diff < 0.1:
                    comp = "几乎相同"
                elif v1 > v2:
                    comp = f"{f1} 高于 {f2}"
                else:
                    comp = f"{f1} 低于 {f2}"
                q = f"请比较化学品“{name}”的{f1}和{f2}，哪个更高？"
                a = f"化学品“{name}”的{f1}为 {v1}℃，{f2}为 {v2}℃，两者相比，{comp}，相差约 {diff:.2f}℃。"
                out.append({"q": q, "a": a, "type": "multi_field"})

        # 生成问答2：燃烧性与数值字段关联分析
        if flm_v is not None and num_fields:
            # 选一个数值字段随机
            f1 = rng.choice(num_fields)
            v1 = fields[f1]
            q = f"化学品“{name}”的燃烧性为“{flm_v}”，其{f1}为多少？这对安全使用有何影响？"
            a = f"化学品“{name}”的燃烧性为“{flm_v}”，其{f1}为 {v1}℃。通常，{f1}较低可能意味着化学品更易挥发或燃烧，需加强安全防护措施，避免火源接近。"
            out.append({"q": q, "a": a, "type": "reasoning"})

        # 若未生成足够问答，尝试生成燃烧性与闪点的对比问答
        if len(out) < 2 and flm_v is not None and fp_v is not None:
            q = f"化学品“{name}”的闪点为 {fp_v}℃，燃烧性为“{flm_v}”，请说明其安全性能。"
            a = f"化学品“{name}”的闪点为 {fp_v}℃，燃烧性为“{flm_v}”。闪点较低通常表示化学品易燃，结合其燃烧性，使用时应特别注意防火安全，避免高温和明火环境。"
            out.append({"q": q, "a": a, "type": "scenario"})

        # 限制每条记录最多生成2条问答
        if len(out) > 2:
            out = out[:2]

    return out