# Generated by build_qa_codegen.py
# strategy: protective_measures_reasoning
# func_name: gen_protective_measures_reasoning
# expected_per_row: 4

import random

def gen_protective_measures_reasoning(rows, rng):
    """rows: list[dict]，每个 dict 是 CSV 一行已清洗数据；rng: random.Random 实例。"""
    def is_empty(val):
        return val in ("", "无", "无资料", "无意义", "未制定标准", "未制订标准", "尚不明确", "暂无", "未提供", "-", "—")
    
    out = []
    for row in rows:
        # 过滤空字段
        eng_protect = row.get("工程防护", "")
        resp_protect = row.get("呼吸系统防护", "")
        hand_protect = row.get("手防护", "")
        other_protect = row.get("其他防护", "")
        body_protect = row.get("身体防护", "")
        chem_name = row.get("_主名", "")
        
        if is_empty(eng_protect) and is_empty(resp_protect) and is_empty(hand_protect) and is_empty(other_protect) and is_empty(body_protect):
            continue
        if is_empty(chem_name):
            chem_name = ""
        
        # 组合信息，去重
        measures = []
        for val in (eng_protect, resp_protect, hand_protect, other_protect, body_protect):
            if not is_empty(val):
                measures.append(val.strip())
        # 去重且保持顺序
        seen = set()
        measures_unique = []
        for m in measures:
            if m not in seen:
                seen.add(m)
                measures_unique.append(m)
        
        # 生成多条QA，围绕防护措施推荐和理由
        # 设计4条QA，涵盖单字段、多字段、推理和总结
        qas = []
        
        # 1 单字段问答：工程防护措施
        if not is_empty(eng_protect):
            q = f"针对化学品{chem_name}，有哪些工程防护措施推荐？"
            a = f"对于化学品{chem_name}，推荐的工程防护措施包括：{eng_protect}。这些措施有助于减少有害物质的扩散和人员暴露。"
            qas.append({"q": q, "a": a, "type": "single_field"})
        
        # 2 单字段问答：呼吸系统防护
        if not is_empty(resp_protect):
            q = f"化学品{chem_name}的呼吸系统防护应如何选择？"
            a = f"针对化学品{chem_name}，呼吸系统防护建议为：{resp_protect}。这些防护措施能够有效防止有害气体或粉尘的吸入，保障呼吸安全。"
            qas.append({"q": q, "a": a, "type": "single_field"})
        
        # 3 多字段推理问答：综合个人防护措施推荐
        if len(measures_unique) >= 2:
            q = f"请综合化学品{chem_name}的多种防护措施，推荐合理的个人防护装备和安全管理建议。"
            a = f"针对化学品{chem_name}，综合考虑工程防护、呼吸系统防护、手防护、其他防护及身体防护，建议采取以下措施：{'; '.join(measures_unique)}。这些措施共同作用，能够最大限度地保障工作人员的安全和健康。"
            qas.append({"q": q, "a": a, "type": "reasoning"})
        
        # 4 总结型问答：防护措施整体总结
        if len(measures_unique) > 0:
            q = f"总结化学品{chem_name}的个人防护措施及其重要性。"
            a = f"化学品{chem_name}的个人防护措施涵盖了工程控制、呼吸防护、手部及身体防护等多个方面。合理实施这些措施能够有效降低职业暴露风险，保障操作人员的安全，促进安全管理的科学化和规范化。"
            qas.append({"q": q, "a": a, "type": "summary"})
        
        # 按预期数量挑选或补充到4条
        if len(qas) > 4:
            qas = rng.sample(qas, 4)
        elif len(qas) < 4 and len(measures_unique) > 0:
            # 补充单字段问答，优先手防护和身体防护
            if is_empty(hand_protect) is False and all(q["q"].find("手防护")<0 for q in qas):
                q = f"化学品{chem_name}操作时，手部防护有哪些建议？"
                a = f"针对化学品{chem_name}，建议采取手部防护措施：{hand_protect}。有效的手部防护能够防止化学品对皮肤的直接接触和伤害。"
                qas.append({"q": q, "a": a, "type": "single_field"})
            if len(qas) < 4 and is_empty(body_protect) is False and all(q["q"].find("身体防护")<0 for q in qas):
                q = f"化学品{chem_name}的身体防护措施有哪些？"
                a = f"针对化学品{chem_name}，身体防护建议包括：{body_protect}。这些措施有助于减少化学品对身体的危害，保障人员安全。"
                qas.append({"q": q, "a": a, "type": "single_field"})
            # 若仍不足4条，重复已有条目（不理想，但保证条数）
            while len(qas) < 4:
                qas.append(qas[0])
            qas = qas[:4]
        
        out.extend(qas)
    return out