# Generated by build_qa_codegen.py
# strategy: reverse_inference_by_hazard
# func_name: gen_reverse_inference_by_hazard
# expected_per_row: 1

import random

def gen_reverse_inference_by_hazard(rows, rng):
    """rows: list[dict]，每个 dict 是 CSV 一行已清洗数据；rng: random.Random 实例。"""
    empty_values = {"", "无", "无资料", "无意义", "未制定标准", "未制订标准", "尚不明确", "暂无", "未提供", "-", "—"}
    out = []
    for row in rows:
        hazard = row.get("危险特性", "")
        combust = row.get("燃烧性", "")
        polymer = row.get("聚合危害", "")
        stability = row.get("稳定性", "")
        main_name = row.get("_主名", "")

        # 判断字段是否有效
        if (hazard in empty_values or combust in empty_values) and (polymer in empty_values and stability in empty_values):
            # 如果所有目标字段都无有效数据，跳过
            continue
        
        # 生成问题和答案，基于危险特性和燃烧性优先
        q = ""
        a = ""
        # 优先用危险特性和燃烧性做反向推断
        if hazard not in empty_values and combust not in empty_values:
            q = f"根据危险特性和燃烧性，推断该化学品的可能特征或名称有哪些？"
            a = f"该化学品“{main_name}”的危险特性描述为：“{hazard}”，燃烧性为“{combust}”，由此可推断其具有较强的燃烧或爆炸危险性，可能属于易燃易爆的化学品类别。"
        elif hazard not in empty_values:
            q = f"根据危险特性，推断该化学品的可能特征或名称？"
            a = f"该化学品“{main_name}”的危险特性为：“{hazard}”，表明其具有特定的危险性质，可能涉及燃烧、爆炸或剧烈反应等风险。"
        elif combust not in empty_values:
            q = f"根据燃烧性，推断该化学品的可能特征或名称？"
            a = f"该化学品“{main_name}”的燃烧性为“{combust}”，说明其在火源或高温条件下可能发生燃烧或助燃反应。"
        elif polymer not in empty_values or stability not in empty_values:
            q = f"根据聚合危害或稳定性，推断该化学品的可能特征或名称？"
            parts = []
            if polymer not in empty_values:
                parts.append(f"聚合危害为“{polymer}”")
            if stability not in empty_values:
                parts.append(f"稳定性为“{stability}”")
            desc = "，".join(parts)
            a = f"该化学品“{main_name}”的{desc}，表明其在储存或使用过程中可能存在聚合反应或稳定性问题，需注意相关安全防护。"
            q = f"根据聚合危害和稳定性，推断该化学品的可能特征或名称？"
        else:
            # 无法生成有效问答，跳过
            continue
        
        # 答案长度限制 8~1500字符，问题长度>=6
        if len(q) >= 6 and 8 <= len(a) <= 1500:
            out.append({"q": q, "a": a, "type": "reasoning"})
    return out